SET search_path TO "lsat";

INSERT INTO problems (
  source,
  order_index,
  difficulty,
  difficulty_level,
  category,
  question_text,
  options,
  correct_option,
  explanation,
  solution_steps,
  concept_tags,
  common_errors,
  hint,
  time_recommendation_seconds
) VALUES
(
  'onboarding',
  1,
  'easy',
  2,
  'Logical Reasoning - Main Conclusion',
  'A city council member argues: "Public transit ridership has increased every month since the new bus lanes opened. Therefore, the new bus lanes caused the increase in ridership." Which statement best describes the conclusion?',
  '["Public transit ridership increased every month.", "The new bus lanes caused the increase in ridership.", "The city council opened new bus lanes.", "Public transit is more useful than driving."]'::jsonb,
  1,
  'The conclusion is the claim the argument is trying to prove: that the new bus lanes caused the ridership increase.',
  '[]'::jsonb,
  '["main conclusion","causal reasoning"]'::jsonb,
  '["confusing evidence with conclusion"]'::jsonb,
  'Look for the claim supported by the other sentence.',
  90
),
(
  'onboarding',
  2,
  'easy',
  2,
  'Logical Reasoning - Flaw',
  'A study found that people who drink green tea report lower stress. So drinking green tea must reduce stress. What is the main flaw?',
  '["It ignores the possibility that less-stressed people are more likely to drink green tea.", "It assumes green tea is healthier than coffee.", "It compares two unrelated beverages.", "It fails to define stress scientifically."]'::jsonb,
  0,
  'The argument treats correlation as causation and ignores reverse causation or another explanation.',
  '[]'::jsonb,
  '["flaw","correlation causation"]'::jsonb,
  '["accepting a causal claim too quickly"]'::jsonb,
  'Ask whether the evidence proves direction of cause.',
  90
),
(
  'onboarding',
  3,
  'easy',
  2,
  'Reading Comprehension - Main Point',
  'A passage explains that urban gardens do more than produce food: they build community, improve local environments, and teach residents ecological habits. What is the main point?',
  '["Urban gardens should replace supermarkets.", "Urban gardens have social and environmental value beyond food production.", "Urban gardens are difficult to maintain.", "Urban gardens are only useful in large cities."]'::jsonb,
  1,
  'The passage emphasizes several benefits beyond food production, making that the central idea.',
  '[]'::jsonb,
  '["main point","reading comprehension"]'::jsonb,
  '["choosing a detail instead of the main idea"]'::jsonb,
  'Pick the answer broad enough to cover the whole passage.',
  90
),
(
  'onboarding',
  4,
  'medium',
  5,
  'Logical Reasoning - Necessary Assumption',
  'An editor argues: "The magazine should publish longer investigative pieces because readers say they want deeper reporting." Which assumption is required?',
  '["Readers who want deeper reporting would be willing to read longer investigative pieces.", "Investigative pieces are cheaper to produce than short articles.", "All magazines should publish investigative journalism.", "Readers dislike short articles."]'::jsonb,
  0,
  'The argument depends on connecting the stated preference for deeper reporting to willingness to read longer pieces.',
  '[]'::jsonb,
  '["necessary assumption"]'::jsonb,
  '["choosing an answer that is too strong"]'::jsonb,
  'Negate the answer and see whether the argument falls apart.',
  105
),
(
  'onboarding',
  5,
  'medium',
  5,
  'Logical Reasoning - Strengthen',
  'A researcher claims a new study app improves retention because users scored higher after using it for two weeks. Which finding most strengthens the claim?',
  '["The users were already motivated students.", "A similar group that did not use the app showed no score improvement.", "The app has a colorful interface.", "Some users disliked the reminder feature."]'::jsonb,
  1,
  'A comparison group helps show that the app, not some outside factor, likely caused the improvement.',
  '[]'::jsonb,
  '["strengthen","causal reasoning"]'::jsonb,
  '["choosing irrelevant positive details"]'::jsonb,
  'Look for evidence that rules out an alternative explanation.',
  105
),
(
  'onboarding',
  6,
  'medium',
  5,
  'Reading Comprehension - Inference',
  'A passage states that a policy was popular with voters but criticized by economists for producing long-term inefficiencies. What can be inferred?',
  '["The policy had political appeal despite expert concerns.", "The policy was rejected by voters.", "Economists supported the policy.", "The policy had no short-term benefits."]'::jsonb,
  0,
  'The passage supports the idea that the policy was politically popular while experts raised concerns.',
  '[]'::jsonb,
  '["inference","reading comprehension"]'::jsonb,
  '["overstating what the passage says"]'::jsonb,
  'The correct inference must be directly supported, not merely possible.',
  105
),
(
  'onboarding',
  7,
  'hard',
  8,
  'Logical Reasoning - Weaken',
  'A company claims its four-day workweek increased productivity because output rose after the policy began. Which fact most weakens the claim?',
  '["The company also introduced new automation software at the same time.", "Employees reported enjoying the new schedule.", "The company announced the policy publicly.", "Some managers were initially skeptical."]'::jsonb,
  0,
  'The automation software is an alternative cause of increased output, weakening the claim that the schedule caused it.',
  '[]'::jsonb,
  '["weaken","alternative cause"]'::jsonb,
  '["attacking irrelevant details"]'::jsonb,
  'Find the answer that makes the causal explanation less certain.',
  120
),
(
  'onboarding',
  8,
  'hard',
  8,
  'Logical Reasoning - Sufficient Assumption',
  'Argument: "If a policy reduces housing supply, it raises rents. This zoning rule raises rents. Therefore, this zoning rule reduces housing supply." Which assumption would make the argument valid?',
  '["Any policy that raises rents reduces housing supply.", "All zoning rules are harmful.", "Housing supply sometimes affects rents.", "Rent increases are always temporary."]'::jsonb,
  0,
  'The conclusion reverses the original conditional. The sufficient assumption supplies the missing reverse link.',
  '[]'::jsonb,
  '["sufficient assumption","conditional logic"]'::jsonb,
  '["mistaking necessary and sufficient conditions"]'::jsonb,
  'Translate the argument into if/then form.',
  120
),
(
  'onboarding',
  9,
  'hard',
  8,
  'Reading Comprehension - Function',
  'In a passage, the author first describes a common theory, then presents evidence that complicates it. What is the likely function of the second part?',
  '["To reject the topic as unimportant.", "To qualify or challenge the earlier theory.", "To summarize unrelated background.", "To introduce a new author biography."]'::jsonb,
  1,
  'Evidence that complicates a theory usually qualifies, limits, or challenges that theory.',
  '[]'::jsonb,
  '["function","passage structure"]'::jsonb,
  '["missing the relationship between paragraphs"]'::jsonb,
  'Ask how the later information changes the earlier claim.',
  120
),
(
  'onboarding',
  10,
  'hard',
  8,
  'Logical Reasoning - Parallel Reasoning',
  'Argument pattern: "All certified mediators completed training. Jordan completed training. Therefore, Jordan is a certified mediator." Which flaw matches this pattern?',
  '["All published authors write drafts. Lee writes drafts. Therefore, Lee is a published author.", "All judges know the law. Mira is a judge. Therefore, Mira knows the law.", "Some lawyers are advocates. Dana is a lawyer. Therefore, Dana may be an advocate.", "No interns are partners. Ravi is a partner. Therefore, Ravi is not an intern."]'::jsonb,
  0,
  'Both arguments affirm the consequent: they treat a necessary condition as sufficient.',
  '[]'::jsonb,
  '["parallel reasoning","conditional flaw"]'::jsonb,
  '["matching topic instead of logical structure"]'::jsonb,
  'Match the logical structure, not the subject matter.',
  120
)
ON CONFLICT DO NOTHING;
