-- Core LSAT practice seed.
-- Note: the current schema only has problem_source values like "sat" and does
-- not yet include "lsat". These LSAT problems use source='sat' for compatibility
-- with the existing quiz, progress, and daily quest queries.

INSERT INTO topics (
  slug,
  name,
  icon,
  order_index,
  color_scheme,
  overview,
  learning_objectives,
  sat_relevance,
  difficulty_distribution,
  estimated_total_minutes,
  prerequisites,
  key_concepts,
  pro_tips,
  subject
) VALUES
(
  'logical-reasoning',
  'Logical Reasoning',
  'brain',
  1,
  'indigo',
  'Analyze short arguments, identify assumptions, evaluate evidence, and choose answers that change the argument in predictable ways.',
  '["Identify conclusions and support", "Recognize common flaws", "Evaluate strengthen and weaken answers", "Use conditional logic precisely"]'::jsonb,
  '{"percentageOfTest": 50, "description": "Logical Reasoning is the largest LSAT section and drives much of the adaptive practice plan."}'::jsonb,
  '{"easy": 25, "medium": 50, "hard": 25}'::jsonb,
  180,
  '[]'::jsonb,
  '["Conclusion vs evidence", "Assumptions", "Causal reasoning", "Conditional logic", "Answer choice precision"]'::jsonb,
  '["Prephrase before reading answers", "Separate what is proven from what is possible", "Attack causal claims by looking for alternatives"]'::jsonb,
  'logical-reasoning'
),
(
  'reading-comprehension',
  'Reading Comprehension',
  'book-open',
  2,
  'emerald',
  'Read dense passages for structure, viewpoint, purpose, and precise textual support.',
  '["Track the author''s main point", "Identify paragraph function", "Make supported inferences", "Compare viewpoints across passages"]'::jsonb,
  '{"percentageOfTest": 50, "description": "Reading Comprehension tests structure, inference, detail, and author attitude across dense passages."}'::jsonb,
  '{"easy": 30, "medium": 45, "hard": 25}'::jsonb,
  150,
  '[]'::jsonb,
  '["Main point", "Passage structure", "Inference", "Author attitude", "Comparative reading"]'::jsonb,
  '["Read for role, not memorization", "Tie every answer to passage support", "Avoid answers that are too broad or too strong"]'::jsonb,
  'reading-comprehension'
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  icon = EXCLUDED.icon,
  color_scheme = EXCLUDED.color_scheme,
  overview = EXCLUDED.overview,
  learning_objectives = EXCLUDED.learning_objectives,
  sat_relevance = EXCLUDED.sat_relevance,
  difficulty_distribution = EXCLUDED.difficulty_distribution,
  estimated_total_minutes = EXCLUDED.estimated_total_minutes,
  prerequisites = EXCLUDED.prerequisites,
  key_concepts = EXCLUDED.key_concepts,
  pro_tips = EXCLUDED.pro_tips,
  subject = EXCLUDED.subject;

WITH subtopic_rows(topic_slug, slug, name, order_index, description, objectives, mistakes, tips, difficulty, minutes, overview) AS (
  VALUES
  (
    'logical-reasoning',
    'flaw-questions',
    'Flaw Questions',
    1,
    'Find the reasoning error that prevents an argument from being fully persuasive.',
    '["Separate evidence from conclusion", "Name common flaw patterns", "Match answer choices to the actual logical gap"]'::jsonb,
    '["Choosing a true statement that is not a flaw", "Attacking the topic instead of the reasoning", "Overlooking causal alternatives"]'::jsonb,
    '["Ask what must be true for the conclusion to follow", "Use common flaw labels only after reading the argument carefully"]'::jsonb,
    'medium',
    35,
    '{"definition": "Flaw questions ask what is wrong with an argument''s reasoning.", "realWorldExample": "A manager concludes a policy worked because sales rose, ignoring that a holiday season also began.", "satContext": "On the LSAT, flaw questions reward precision about why the evidence does not prove the conclusion."}'::jsonb
  ),
  (
    'logical-reasoning',
    'assumption-questions',
    'Assumption Questions',
    2,
    'Identify the missing idea that an argument needs in order to work.',
    '["Distinguish necessary from sufficient assumptions", "Use the negation test", "Find missing links between evidence and conclusion"]'::jsonb,
    '["Picking an answer that merely strengthens", "Choosing an assumption that is too broad", "Ignoring the exact conclusion"]'::jsonb,
    '["Negate necessary assumptions", "For sufficient assumptions, make the argument valid"]'::jsonb,
    'medium',
    40,
    '{"definition": "Assumption questions test the unstated bridge between support and conclusion.", "realWorldExample": "A campaign assumes that people who like a policy will actually vote for it.", "satContext": "On the LSAT, assumption questions are central to argument structure."}'::jsonb
  ),
  (
    'logical-reasoning',
    'strengthen-weaken',
    'Strengthen and Weaken',
    3,
    'Evaluate which facts make an argument more or less convincing.',
    '["Spot the argument''s causal or logical vulnerability", "Find alternative explanations", "Choose the answer with direct impact"]'::jsonb,
    '["Choosing background information", "Overvaluing extreme answers", "Missing the exact conclusion being tested"]'::jsonb,
    '["For causal claims, look for controls and alternatives", "For predictions, look for new evidence about reliability"]'::jsonb,
    'medium',
    40,
    '{"definition": "Strengthen and weaken questions ask how new information changes an argument.", "realWorldExample": "A product claim becomes stronger when a similar control group did not improve.", "satContext": "On the LSAT, these questions test whether you understand the argument''s pressure point."}'::jsonb
  ),
  (
    'reading-comprehension',
    'main-point-structure',
    'Main Point and Structure',
    1,
    'Identify the passage''s central claim and how each paragraph contributes to it.',
    '["State the author''s main point", "Track paragraph roles", "Avoid answers that capture only a detail"]'::jsonb,
    '["Choosing a narrow detail", "Ignoring contrast words", "Mistaking another viewpoint for the author''s view"]'::jsonb,
    '["Summarize each paragraph in role language", "Ask why the author included each section"]'::jsonb,
    'medium',
    35,
    '{"definition": "Main point and structure questions test the overall purpose of a passage.", "realWorldExample": "An article can describe an old theory, introduce a challenge, then defend a revised view.", "satContext": "On the LSAT, structure matters because many answers are accurate details but wrong main points."}'::jsonb
  ),
  (
    'reading-comprehension',
    'inference-detail',
    'Inference and Detail',
    2,
    'Choose answers that are directly supported by the passage without overstating it.',
    '["Locate textual support", "Draw modest inferences", "Reject answers that go beyond the passage"]'::jsonb,
    '["Treating a possible claim as proven", "Forgetting qualifiers", "Choosing an answer with one unsupported word"]'::jsonb,
    '["Return to the relevant lines", "Prefer conservative wording when the passage is cautious"]'::jsonb,
    'medium',
    35,
    '{"definition": "Inference and detail questions ask what the passage says or strongly implies.", "realWorldExample": "If an author says a theory is promising but incomplete, it is unsupported to say the author rejects it.", "satContext": "On the LSAT, supported answers are often narrower than they first appear."}'::jsonb
  )
)
INSERT INTO subtopics (
  topic_id,
  slug,
  name,
  order_index,
  description,
  learning_objectives,
  key_formulas,
  common_mistakes,
  tips_and_tricks,
  difficulty,
  estimated_minutes,
  prerequisite_subtopic_slugs,
  conceptual_overview
)
SELECT
  t.id,
  r.slug,
  r.name,
  r.order_index,
  r.description,
  r.objectives,
  '[]'::jsonb,
  r.mistakes,
  r.tips,
  r.difficulty,
  r.minutes,
  '[]'::jsonb,
  r.overview
FROM subtopic_rows r
JOIN topics t ON t.slug = r.topic_slug
ON CONFLICT (topic_id, slug) DO UPDATE SET
  name = EXCLUDED.name,
  order_index = EXCLUDED.order_index,
  description = EXCLUDED.description,
  learning_objectives = EXCLUDED.learning_objectives,
  common_mistakes = EXCLUDED.common_mistakes,
  tips_and_tricks = EXCLUDED.tips_and_tricks,
  difficulty = EXCLUDED.difficulty,
  estimated_minutes = EXCLUDED.estimated_minutes,
  conceptual_overview = EXCLUDED.conceptual_overview;

WITH problem_rows(topic_slug, subtopic_slug, order_index, difficulty, difficulty_level, question_text, options, correct_option, explanation, hint, tags) AS (
  VALUES
  ('logical-reasoning', 'flaw-questions', 1, 'easy', 2,
   'A bakery notes that sales rose after it changed its logo. It concludes that the new logo caused the increase in sales. What is the main flaw?',
   '["It assumes that because one event followed another, the first caused the second.", "It assumes bakeries never benefit from advertising.", "It overlooks whether customers liked the old logo.", "It fails to explain how logos are designed."]'::jsonb,
   0,
   'The argument treats sequence as proof of causation and ignores other possible causes of the sales increase.',
   'Ask whether another factor could explain the sales increase.',
   '["flaw", "causal reasoning"]'::jsonb),
  ('logical-reasoning', 'flaw-questions', 2, 'medium', 4,
   'All successful applicants submitted recommendation letters. Mira submitted recommendation letters. Therefore, Mira will be a successful applicant. The reasoning is flawed because it',
   '["confuses a condition required for success with a condition sufficient for success.", "assumes no applicant can submit more than one letter.", "draws a conclusion about all applicants from one example.", "rejects evidence without explanation."]'::jsonb,
   0,
   'The argument treats a necessary condition as if it guarantees the result.',
   'Translate the relationship into if/then terms.',
   '["flaw", "conditional logic"]'::jsonb),
  ('logical-reasoning', 'flaw-questions', 3, 'medium', 6,
   'A critic argues that a novel cannot be valuable because many readers found it confusing. Which flaw does the argument commit?',
   '["It assumes that a work cannot be valuable if some readers struggle to understand it.", "It assumes all readers read the entire novel.", "It ignores the author''s biography.", "It treats popularity as the only measure of sales."]'::jsonb,
   0,
   'The argument relies on an unsupported link between difficulty and lack of value.',
   'Find the hidden standard the argument is using.',
   '["flaw", "unsupported standard"]'::jsonb),
  ('logical-reasoning', 'flaw-questions', 4, 'hard', 8,
   'A study found that neighborhoods with more parks have lower asthma rates, so building parks will reduce asthma. The argument is most vulnerable because it',
   '["fails to rule out that wealthier neighborhoods both have more parks and better health outcomes.", "assumes parks are less expensive than clinics.", "does not specify the number of trees in each park.", "compares asthma with unrelated illnesses."]'::jsonb,
   0,
   'A third factor could explain both park availability and lower asthma rates.',
   'For causal arguments, test for third variables.',
   '["flaw", "correlation causation"]'::jsonb),

  ('logical-reasoning', 'assumption-questions', 1, 'easy', 2,
   'A council should extend library hours because many residents say they want more evening study spaces. Which assumption is required?',
   '["Residents who want evening study spaces would use the library during extended hours.", "Libraries should be open all night.", "The council has already approved the budget.", "Residents prefer libraries to parks."]'::jsonb,
   0,
   'The argument needs a bridge between wanting evening study spaces and using extended library hours.',
   'Negate the answer and see whether the argument loses support.',
   '["necessary assumption"]'::jsonb),
  ('logical-reasoning', 'assumption-questions', 2, 'medium', 4,
   'A museum should digitize its archive because doing so will make the collection accessible worldwide. The argument assumes that',
   '["people outside the museum''s region would be able to access the digital archive.", "all museums have identical archives.", "physical archives are always unreliable.", "digitizing an archive requires no staff time."]'::jsonb,
   0,
   'Worldwide accessibility depends on people outside the region actually being able to access the digital archive.',
   'Look for the missing link between the plan and the claimed benefit.',
   '["necessary assumption"]'::jsonb),
  ('logical-reasoning', 'assumption-questions', 3, 'medium', 6,
   'If a training program improves retention, the company should adopt it. The pilot program improved retention. Therefore, the company should adopt it. Which assumption would most help justify the conclusion?',
   '["The pilot program is representative of how the program would work companywide.", "No employee dislikes training.", "Retention is the only goal the company has.", "The pilot program was shorter than the full program."]'::jsonb,
   0,
   'The argument assumes results from the pilot can be generalized to the broader company.',
   'Ask what must connect the evidence to the recommendation.',
   '["assumption", "representativeness"]'::jsonb),
  ('logical-reasoning', 'assumption-questions', 4, 'hard', 8,
   'A city should not build the tunnel because any project that exceeds its budget should be rejected, and the tunnel is likely to exceed its budget. Which assumption is needed?',
   '["A project likely to exceed its budget should be treated as a project that exceeds its budget for purposes of rejection.", "The tunnel would not reduce traffic.", "Every city project exceeds its budget.", "Budget estimates are always accurate."]'::jsonb,
   0,
   'The evidence concerns what is likely, while the stated rule concerns what actually exceeds budget; the assumption connects those ideas.',
   'Watch for shifts between certainty and likelihood.',
   '["necessary assumption", "scope shift"]'::jsonb),

  ('logical-reasoning', 'strengthen-weaken', 1, 'easy', 2,
   'A school claims its new tutoring program improved test scores because participants improved after eight weeks. Which fact most strengthens the claim?',
   '["Students with similar starting scores who did not join the program improved much less.", "Some students enjoyed the tutors.", "The program met twice a week.", "The school advertised the program online."]'::jsonb,
   0,
   'A comparison group helps show the program, rather than another factor, caused the improvement.',
   'Look for evidence that controls for alternative explanations.',
   '["strengthen", "causal reasoning"]'::jsonb),
  ('logical-reasoning', 'strengthen-weaken', 2, 'medium', 4,
   'A company says remote work caused productivity to rise because output increased after remote work began. Which fact most weakens the claim?',
   '["The company also replaced its slow project software at the same time.", "Employees saved commuting time.", "Some managers prefer office work.", "Output is measured weekly."]'::jsonb,
   0,
   'The software replacement is an alternative cause of the productivity increase.',
   'Find a fact that makes the proposed cause less certain.',
   '["weaken", "alternative cause"]'::jsonb),
  ('logical-reasoning', 'strengthen-weaken', 3, 'medium', 6,
   'A nutritionist argues that a new breakfast plan improves concentration because students using it reported better focus. Which answer most weakens the argument?',
   '["Students chose whether to use the plan, and those who chose it were already more motivated.", "The plan includes fruit.", "Some students ate breakfast before the study.", "The nutritionist works at a school."]'::jsonb,
   0,
   'Self-selection creates an alternative explanation for the reported focus.',
   'Consider whether the groups were comparable before the change.',
   '["weaken", "selection bias"]'::jsonb),
  ('logical-reasoning', 'strengthen-weaken', 4, 'hard', 8,
   'A historian argues that a newly found letter was written by Author X because it uses a phrase common in X''s published work. Which fact most weakens the argument?',
   '["The phrase was widely used by many writers in the same region during that period.", "Author X wrote many letters.", "The letter is stored in a university archive.", "Some of Author X''s works were published anonymously."]'::jsonb,
   0,
   'If many writers used the phrase, it is weak evidence that Author X wrote the letter.',
   'Ask whether the evidence uniquely supports the conclusion.',
   '["weaken", "evidence strength"]'::jsonb),

  ('reading-comprehension', 'main-point-structure', 1, 'easy', 2,
   'A passage argues that urban tree planting should be evaluated not only by number of trees planted, but by long-term survival, shade coverage, and equitable distribution. What is the main point?',
   '["Tree-planting programs require broader success measures than planting totals alone.", "Cities should stop planting trees.", "Shade coverage is impossible to measure.", "Only wealthy neighborhoods need trees."]'::jsonb,
   0,
   'The passage centers on broader criteria for evaluating tree-planting programs.',
   'Choose the answer broad enough to cover all major parts of the passage.',
   '["main point", "structure"]'::jsonb),
  ('reading-comprehension', 'main-point-structure', 2, 'medium', 4,
   'A passage first presents a theory about language change, then describes evidence that limits where the theory applies. The second part primarily functions to',
   '["qualify the scope of the theory.", "prove that language never changes.", "introduce a biography of the theorist.", "summarize an unrelated debate."]'::jsonb,
   0,
   'Evidence that limits applicability qualifies the original theory.',
   'Describe what the later paragraph does to the earlier claim.',
   '["function", "passage structure"]'::jsonb),
  ('reading-comprehension', 'main-point-structure', 3, 'medium', 6,
   'A passage describes a legal reform, notes its intended benefits, and then discusses implementation problems. The passage is best described as',
   '["a balanced assessment of a reform with both goals and practical challenges.", "a rejection of all legal reform.", "a chronological biography of a judge.", "a technical manual for lawyers."]'::jsonb,
   0,
   'The passage weighs benefits and implementation problems rather than taking an extreme position.',
   'Avoid answers that overstate the author''s attitude.',
   '["main point", "author attitude"]'::jsonb),
  ('reading-comprehension', 'main-point-structure', 4, 'hard', 8,
   'A passage introduces a dominant explanation for a scientific pattern, then argues that the explanation overlooks regional variation. The author''s main purpose is to',
   '["challenge an explanation by showing that it fails to account for important variation.", "catalog every regional example of the pattern.", "argue that scientific explanations are useless.", "describe the author''s fieldwork methods only."]'::jsonb,
   0,
   'The passage challenges a dominant explanation by pointing to an important limitation.',
   'Main purpose answers should capture both the target and the author''s action.',
   '["main purpose", "critique"]'::jsonb),

  ('reading-comprehension', 'inference-detail', 1, 'easy', 2,
   'A passage says that a policy reduced commute times in central districts but had little effect in outer districts. Which inference is best supported?',
   '["The policy''s effects varied by location.", "The policy failed everywhere.", "Outer districts had no commuters.", "Central districts opposed the policy."]'::jsonb,
   0,
   'The passage directly supports that the effect differed between central and outer districts.',
   'Keep the inference modest and text-based.',
   '["inference", "detail"]'::jsonb),
  ('reading-comprehension', 'inference-detail', 2, 'medium', 4,
   'A passage states that early reviews praised a composer''s originality, while later critics emphasized the composer''s debt to earlier traditions. What can be inferred?',
   '["Critical views of the composer changed in emphasis over time.", "Later critics denied the composer had any originality.", "Early reviewers knew nothing about music.", "The composer rejected all earlier traditions."]'::jsonb,
   0,
   'The passage supports a shift in critical emphasis, not an absolute reversal.',
   'Watch for answers that make the passage more extreme.',
   '["inference", "author claims"]'::jsonb),
  ('reading-comprehension', 'inference-detail', 3, 'medium', 6,
   'A passage says researchers welcomed a new dataset but cautioned that it excluded informal transactions. Which statement is most supported?',
   '["The dataset is useful but incomplete for some research questions.", "The dataset has no scholarly value.", "Informal transactions are easier to measure than formal ones.", "Researchers rejected the dataset."]'::jsonb,
   0,
   'The researchers welcomed the dataset while noting a limitation.',
   'Combine both sides of the author''s statement.',
   '["inference", "qualification"]'::jsonb),
  ('reading-comprehension', 'inference-detail', 4, 'hard', 8,
   'A passage argues that a court decision was narrow because it resolved the case without addressing the broader constitutional question. Which detail would best support that description?',
   '["The decision applied a procedural rule and explicitly declined to decide the constitutional issue.", "The decision was reported in several newspapers.", "The court heard oral argument for two hours.", "One justice previously taught constitutional law."]'::jsonb,
   0,
   'A procedural ruling that avoids the constitutional issue directly supports calling the decision narrow.',
   'Support answers must connect to the exact description in the question.',
   '["detail", "support"]'::jsonb)
)
INSERT INTO problems (
  source,
  subtopic_id,
  topic_slug,
  subtopic_slug,
  order_index,
  difficulty,
  difficulty_level,
  question_text,
  options,
  correct_option,
  explanation,
  solution_steps,
  concept_tags,
  common_errors,
  hint,
  detailed_hint,
  time_recommendation_seconds,
  sat_frequency
)
SELECT
  'sat'::problem_source,
  st.id,
  p.topic_slug,
  p.subtopic_slug,
  p.order_index,
  p.difficulty,
  p.difficulty_level,
  p.question_text,
  p.options,
  p.correct_option,
  p.explanation,
  '[]'::jsonb,
  p.tags,
  '[]'::jsonb,
  p.hint,
  p.hint,
  95,
  'core'
FROM problem_rows p
JOIN topics t ON t.slug = p.topic_slug
JOIN subtopics st ON st.topic_id = t.id AND st.slug = p.subtopic_slug
ON CONFLICT DO NOTHING;
